sudo: false
language: python
python: 3.4.6
cache:
  pip: true
  directories:
    - docs/_build

script:
  - make html SPHINXOPTS=-W

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never

branches:
  exclude:
    - /^sils\//
